In [ ]:
import numpy as np
import numpy.random as random

In [86]:
def solution(board, moves):
    n_board =random.randint(low=5,high=31,size=1)
    board = random.randint(0,101,(n_board,n_board))
    n_moves = random.randint(low=1,high=1001,size=1)
    moves = random.randint(size=n_moves)
#     board.fill(random.randint(low=0,high=101,size=n))
    N

In [5]:
N=np.arange(5,31)
print(N)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30]


In [80]:
n = random.randint(low =5, high =31, size = 1)
print(n)

[12]


In [90]:
x = random.random([5,5])
print(x)
x.fill(random.randint(low=0,high=101))
print(x)

[[0.46032297 0.02547372 0.56502934 0.79996219 0.71746401]
 [0.32055577 0.78723752 0.41069136 0.35384774 0.53506473]
 [0.49534976 0.05027973 0.29457517 0.15780689 0.53310099]
 [0.41509291 0.72802409 0.62546396 0.06241723 0.47894614]
 [0.79822357 0.14984916 0.2053549  0.17995745 0.76715916]]
[[35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]
 [35. 35. 35. 35. 35.]]


In [92]:
x=random.randint(0,10,(5,5))
print(x)

[[2 9 2 3 9]
 [9 8 7 8 0]
 [1 3 1 1 5]
 [1 6 3 0 8]
 [7 0 1 8 1]]
